#!/usr/bin/python3

import argparse
import sys, select
import signal
import curses
from curses import wrapper

from privy_io import PrivyIO
from privy_ui import ChatUI

def main(stdscr, args):

    io = PrivyIO(args.d, 2324, args.ip)

    def signal_handler(signal, frame):
        io.close_socket()
        sys.exit(0)

    signal.signal(signal.SIGINT, signal_handler)

    stdscr.clear()
    ui = ChatUI(stdscr)
    name = "me"
    ui.userlist.append(name)
    ui.redraw_userlist()
    inp = ""
    while inp != "/quit":
        inp = ui.wait_input()
        ui.chatbuffer_add("me: " + inp)
        io.send(inp)
        out = io.receive()
        if out:
            ui.chatbuffer_add("them: " + out)

    io.close_socket()


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', help='act as the server', action='store_true')
    parser.add_argument('ip', nargs='?', help='ip to send message to')

    args = parser.parse_args()

    wrapper(main, args)


