#!/usr/bin/python3

import argparse
import sys, select
import signal
import curses
from curses import wrapper

from privy_io import *
from privy_ui import ChatUI

def main(stdscr, args):

    s = setup_socket()

    def signal_handler(signal, frame):
        s.close()
        sys.exit(0)

    signal.signal(signal.SIGINT, signal_handler)

    TCP_PORT = 21131
    if args.d:
        s = config_server_socket(s, TCP_PORT)
    else:
        ip = args.ip
        if not ip:
            parser.print_help()
            sys.exit(0)
        config_client_socket(s, ip, TCP_PORT)

    s.setblocking(0)

    stdscr.clear()
    ui = ChatUI(stdscr)
    name = "me"
    ui.userlist.append(name)
    ui.redraw_userlist()
    inp = ""
    while inp != "/quit":
        inp = ui.wait_input()
        ui.chatbuffer_add("me: " + inp)
        send(s, inp)
        out = receive(s)
        if out:
            ui.chatbuffer_add("them: " + out)

    s.close()


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', help='act as the server', action='store_true')
    parser.add_argument('ip', nargs='?', help='ip to send message to')

    args = parser.parse_args()

    wrapper(main, args)


